# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main", feature/*, fix/* ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      env: 
        MUSIXMATCH_APIKEY: ${{ secrets.MUSIXMATCH_APIKEY }}
      run: swift test --enable-code-coverage
    - name: Swift Coverage Conversion
      run: llvm-cov export -format="lcov" .build/debug/MusixmatchAPIPackageTests.xctest -instr-profile .build/debug/codecov/default.profdata > info.lcov      
    - name: Upload coverage to Codecov
      env: 
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: bash <(curl -s https://codecov.io/bash) -J 'MusixmatchAPI'
