# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
#  push:
#    branches: [ "main", feature/*, fix/* ]
  pull_request:
    branches: [ "main", feature/*, fix/* ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: swift build -v
    - name: Run tests
      env: 
          MUSIXMATCH_APIKEY: ${{ secrets.MUSIXMATCH_APIKEY }}
      run: swift test --enable-code-coverage
    - name: Upload coverage to Codecov
      env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      # uses: codecov/codecov-action@v1.2.1
      run: |
        # Replace `linux` below with the appropriate OS
        # Options are `alpine`, `linux`, `macos`, `windows`
        curl -Os https://cli.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov --verbose upload-process --fail-on-error -t ${{ secrets.CODECOV_TOKEN }} -n 'service'-${{ github.run_id }} -F service -f coverage-service.xml
